package com.idc.hes;

// Generated Mar 10, 2016 5:20:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * HesLightingCategoryPackages generated by hbm2java
 */
public class HesLightingCategoryPackages implements java.io.Serializable {

	private long id;
	private HesLightingCategories hesLightingCategories;
	private String displayText;
	private String seoName;
	private String shortDescription;
	private String longDescription;
	private String image1Url;
	private String image1AltText;
	private String image2Url;
	private String image2AltText;
	private String image3Url;
	private String image3AltText;
	private String image4Url;
	private String image4AltText;
	private String image5Url;
	private String image5AltText;
	private String image6Url;
	private String image6AltText;
	private String image7Url;
	private String image7AltText;
	private String image8Url;
	private String image8AltText;
	private Integer seqNo;
	private Set<HesLightingCategoryPackageItems> hesLightingCategoryPackageItemses = new HashSet<HesLightingCategoryPackageItems>(
			0);

	public HesLightingCategoryPackages() {
	}

	public HesLightingCategoryPackages(long id,
			HesLightingCategories hesLightingCategories, String displayText,
			String shortDescription, String longDescription) {
		this.id = id;
		this.hesLightingCategories = hesLightingCategories;
		this.displayText = displayText;
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
	}

	public HesLightingCategoryPackages(
			long id,
			HesLightingCategories hesLightingCategories,
			String displayText,
			String seoName,
			String shortDescription,
			String longDescription,
			String image1Url,
			String image1AltText,
			String image2Url,
			String image2AltText,
			String image3Url,
			String image3AltText,
			String image4Url,
			String image4AltText,
			String image5Url,
			String image5AltText,
			String image6Url,
			String image6AltText,
			String image7Url,
			String image7AltText,
			String image8Url,
			String image8AltText,
			Integer seqNo,
			Set<HesLightingCategoryPackageItems> hesLightingCategoryPackageItemses) {
		this.id = id;
		this.hesLightingCategories = hesLightingCategories;
		this.displayText = displayText;
		this.seoName = seoName;
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
		this.image1Url = image1Url;
		this.image1AltText = image1AltText;
		this.image2Url = image2Url;
		this.image2AltText = image2AltText;
		this.image3Url = image3Url;
		this.image3AltText = image3AltText;
		this.image4Url = image4Url;
		this.image4AltText = image4AltText;
		this.image5Url = image5Url;
		this.image5AltText = image5AltText;
		this.image6Url = image6Url;
		this.image6AltText = image6AltText;
		this.image7Url = image7Url;
		this.image7AltText = image7AltText;
		this.image8Url = image8Url;
		this.image8AltText = image8AltText;
		this.seqNo = seqNo;
		this.hesLightingCategoryPackageItemses = hesLightingCategoryPackageItemses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public HesLightingCategories getHesLightingCategories() {
		return this.hesLightingCategories;
	}

	public void setHesLightingCategories(
			HesLightingCategories hesLightingCategories) {
		this.hesLightingCategories = hesLightingCategories;
	}

	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	public String getImage1Url() {
		return this.image1Url;
	}

	public void setImage1Url(String image1Url) {
		this.image1Url = image1Url;
	}

	public String getImage1AltText() {
		return this.image1AltText;
	}

	public void setImage1AltText(String image1AltText) {
		this.image1AltText = image1AltText;
	}

	public String getImage2Url() {
		return this.image2Url;
	}

	public void setImage2Url(String image2Url) {
		this.image2Url = image2Url;
	}

	public String getImage2AltText() {
		return this.image2AltText;
	}

	public void setImage2AltText(String image2AltText) {
		this.image2AltText = image2AltText;
	}

	public String getImage3Url() {
		return this.image3Url;
	}

	public void setImage3Url(String image3Url) {
		this.image3Url = image3Url;
	}

	public String getImage3AltText() {
		return this.image3AltText;
	}

	public void setImage3AltText(String image3AltText) {
		this.image3AltText = image3AltText;
	}

	public String getImage4Url() {
		return this.image4Url;
	}

	public void setImage4Url(String image4Url) {
		this.image4Url = image4Url;
	}

	public String getImage4AltText() {
		return this.image4AltText;
	}

	public void setImage4AltText(String image4AltText) {
		this.image4AltText = image4AltText;
	}

	public String getImage5Url() {
		return this.image5Url;
	}

	public void setImage5Url(String image5Url) {
		this.image5Url = image5Url;
	}

	public String getImage5AltText() {
		return this.image5AltText;
	}

	public void setImage5AltText(String image5AltText) {
		this.image5AltText = image5AltText;
	}

	public String getImage6Url() {
		return this.image6Url;
	}

	public void setImage6Url(String image6Url) {
		this.image6Url = image6Url;
	}

	public String getImage6AltText() {
		return this.image6AltText;
	}

	public void setImage6AltText(String image6AltText) {
		this.image6AltText = image6AltText;
	}

	public String getImage7Url() {
		return this.image7Url;
	}

	public void setImage7Url(String image7Url) {
		this.image7Url = image7Url;
	}

	public String getImage7AltText() {
		return this.image7AltText;
	}

	public void setImage7AltText(String image7AltText) {
		this.image7AltText = image7AltText;
	}

	public String getImage8Url() {
		return this.image8Url;
	}

	public void setImage8Url(String image8Url) {
		this.image8Url = image8Url;
	}

	public String getImage8AltText() {
		return this.image8AltText;
	}

	public void setImage8AltText(String image8AltText) {
		this.image8AltText = image8AltText;
	}

	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	public Set<HesLightingCategoryPackageItems> getHesLightingCategoryPackageItemses() {
		return this.hesLightingCategoryPackageItemses;
	}

	public void setHesLightingCategoryPackageItemses(
			Set<HesLightingCategoryPackageItems> hesLightingCategoryPackageItemses) {
		this.hesLightingCategoryPackageItemses = hesLightingCategoryPackageItemses;
	}

}
