package com.idc.hes;

// Generated Mar 10, 2016 5:20:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HesRequests generated by hbm2java
 */
public class HesRequests implements java.io.Serializable {

	private long id;
	private String customerCompany;
	private String customerName;
	private String customerAddress;
	private String customerPhone;
	private String customerAltPhone;
	private String customerEmail;
	private Date requestedDeliveryDate;
	private String specialInstructions;
	private Date requestDate;
	private Set<HesRequestDetails> hesRequestDetailses = new HashSet<HesRequestDetails>(
			0);

	public HesRequests() {
	}

	public HesRequests(long id, String customerCompany, String customerName,
			String customerAddress, String customerPhone,
			String customerAltPhone, String customerEmail,
			Date requestedDeliveryDate, Date requestDate) {
		this.id = id;
		this.customerCompany = customerCompany;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerPhone = customerPhone;
		this.customerAltPhone = customerAltPhone;
		this.customerEmail = customerEmail;
		this.requestedDeliveryDate = requestedDeliveryDate;
		this.requestDate = requestDate;
	}

	public HesRequests(long id, String customerCompany, String customerName,
			String customerAddress, String customerPhone,
			String customerAltPhone, String customerEmail,
			Date requestedDeliveryDate, String specialInstructions,
			Date requestDate, Set<HesRequestDetails> hesRequestDetailses) {
		this.id = id;
		this.customerCompany = customerCompany;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerPhone = customerPhone;
		this.customerAltPhone = customerAltPhone;
		this.customerEmail = customerEmail;
		this.requestedDeliveryDate = requestedDeliveryDate;
		this.specialInstructions = specialInstructions;
		this.requestDate = requestDate;
		this.hesRequestDetailses = hesRequestDetailses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCustomerCompany() {
		return this.customerCompany;
	}

	public void setCustomerCompany(String customerCompany) {
		this.customerCompany = customerCompany;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public String getCustomerAltPhone() {
		return this.customerAltPhone;
	}

	public void setCustomerAltPhone(String customerAltPhone) {
		this.customerAltPhone = customerAltPhone;
	}

	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public Date getRequestedDeliveryDate() {
		return this.requestedDeliveryDate;
	}

	public void setRequestedDeliveryDate(Date requestedDeliveryDate) {
		this.requestedDeliveryDate = requestedDeliveryDate;
	}

	public String getSpecialInstructions() {
		return this.specialInstructions;
	}

	public void setSpecialInstructions(String specialInstructions) {
		this.specialInstructions = specialInstructions;
	}

	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	public Set<HesRequestDetails> getHesRequestDetailses() {
		return this.hesRequestDetailses;
	}

	public void setHesRequestDetailses(
			Set<HesRequestDetails> hesRequestDetailses) {
		this.hesRequestDetailses = hesRequestDetailses;
	}

}
