package com.idc.hes;

// Generated Mar 10, 2016 5:20:06 PM by Hibernate Tools 4.0.0

/**
 * HesRequestDetails generated by hbm2java
 */
public class HesRequestDetails implements java.io.Serializable {

	private long id;
	private HesRequests hesRequests;
	private String data;

	public HesRequestDetails() {
	}

	public HesRequestDetails(long id, HesRequests hesRequests, String data) {
		this.id = id;
		this.hesRequests = hesRequests;
		this.data = data;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public HesRequests getHesRequests() {
		return this.hesRequests;
	}

	public void setHesRequests(HesRequests hesRequests) {
		this.hesRequests = hesRequests;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
