package com.idc.hes;

// Generated Mar 10, 2016 5:20:06 PM by Hibernate Tools 4.0.0

/**
 * HesTruckCategoryPackageItems generated by hbm2java
 */
public class HesTruckCategoryPackageItems implements java.io.Serializable {

	private long id;
	private HesTruckCategoryPackages hesTruckCategoryPackages;
	private String displayText;
	private String seoName;
	private Integer defaultCount;
	private Integer priority;
	private Integer seqNo;

	public HesTruckCategoryPackageItems() {
	}

	public HesTruckCategoryPackageItems(long id,
			HesTruckCategoryPackages hesTruckCategoryPackages,
			String displayText) {
		this.id = id;
		this.hesTruckCategoryPackages = hesTruckCategoryPackages;
		this.displayText = displayText;
	}

	public HesTruckCategoryPackageItems(long id,
			HesTruckCategoryPackages hesTruckCategoryPackages,
			String displayText, String seoName, Integer defaultCount,
			Integer priority, Integer seqNo) {
		this.id = id;
		this.hesTruckCategoryPackages = hesTruckCategoryPackages;
		this.displayText = displayText;
		this.seoName = seoName;
		this.defaultCount = defaultCount;
		this.priority = priority;
		this.seqNo = seqNo;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public HesTruckCategoryPackages getHesTruckCategoryPackages() {
		return this.hesTruckCategoryPackages;
	}

	public void setHesTruckCategoryPackages(
			HesTruckCategoryPackages hesTruckCategoryPackages) {
		this.hesTruckCategoryPackages = hesTruckCategoryPackages;
	}

	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

	public Integer getDefaultCount() {
		return this.defaultCount;
	}

	public void setDefaultCount(Integer defaultCount) {
		this.defaultCount = defaultCount;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

}
