package com.idc.hes;

// Generated Mar 10, 2016 5:41:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HesGripCategoryPackages generated by hbm2java
 */
@Entity
@Table(name = "hes_grip_category_packages", catalog = "hes_db")
public class HesGripCategoryPackages implements java.io.Serializable {

	private long id;
	private HesGripCategories hesGripCategories;
	private String displayText;
	private String seoName;
	private String shortDescription;
	private String longDescription;
	private String image1Url;
	private String image1AltText;
	private String image2Url;
	private String image2AltText;
	private String image3Url;
	private String image3AltText;
	private String image4Url;
	private String image4AltText;
	private String image5Url;
	private String image5AltText;
	private String image6Url;
	private String image6AltText;
	private String image7Url;
	private String image7AltText;
	private String image8Url;
	private String image8AltText;
	private Integer seqNo;
	private Set hesGripCategoryPackageItemses = new HashSet(0);

	public HesGripCategoryPackages() {
	}

	public HesGripCategoryPackages(long id,
			HesGripCategories hesGripCategories, String displayText,
			String shortDescription, String longDescription) {
		this.id = id;
		this.hesGripCategories = hesGripCategories;
		this.displayText = displayText;
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
	}

	public HesGripCategoryPackages(long id,
			HesGripCategories hesGripCategories, String displayText,
			String seoName, String shortDescription, String longDescription,
			String image1Url, String image1AltText, String image2Url,
			String image2AltText, String image3Url, String image3AltText,
			String image4Url, String image4AltText, String image5Url,
			String image5AltText, String image6Url, String image6AltText,
			String image7Url, String image7AltText, String image8Url,
			String image8AltText, Integer seqNo,
			Set hesGripCategoryPackageItemses) {
		this.id = id;
		this.hesGripCategories = hesGripCategories;
		this.displayText = displayText;
		this.seoName = seoName;
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
		this.image1Url = image1Url;
		this.image1AltText = image1AltText;
		this.image2Url = image2Url;
		this.image2AltText = image2AltText;
		this.image3Url = image3Url;
		this.image3AltText = image3AltText;
		this.image4Url = image4Url;
		this.image4AltText = image4AltText;
		this.image5Url = image5Url;
		this.image5AltText = image5AltText;
		this.image6Url = image6Url;
		this.image6AltText = image6AltText;
		this.image7Url = image7Url;
		this.image7AltText = image7AltText;
		this.image8Url = image8Url;
		this.image8AltText = image8AltText;
		this.seqNo = seqNo;
		this.hesGripCategoryPackageItemses = hesGripCategoryPackageItemses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_category_id", nullable = false)
	public HesGripCategories getHesGripCategories() {
		return this.hesGripCategories;
	}

	public void setHesGripCategories(HesGripCategories hesGripCategories) {
		this.hesGripCategories = hesGripCategories;
	}

	@Column(name = "display_text", nullable = false)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "seo_name")
	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

	@Column(name = "short_description", nullable = false, length = 500)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "long_description", nullable = false, length = 2000)
	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	@Column(name = "image_1_url")
	public String getImage1Url() {
		return this.image1Url;
	}

	public void setImage1Url(String image1Url) {
		this.image1Url = image1Url;
	}

	@Column(name = "image_1_alt_text", length = 60)
	public String getImage1AltText() {
		return this.image1AltText;
	}

	public void setImage1AltText(String image1AltText) {
		this.image1AltText = image1AltText;
	}

	@Column(name = "image_2_url")
	public String getImage2Url() {
		return this.image2Url;
	}

	public void setImage2Url(String image2Url) {
		this.image2Url = image2Url;
	}

	@Column(name = "image_2_alt_text", length = 60)
	public String getImage2AltText() {
		return this.image2AltText;
	}

	public void setImage2AltText(String image2AltText) {
		this.image2AltText = image2AltText;
	}

	@Column(name = "image_3_url")
	public String getImage3Url() {
		return this.image3Url;
	}

	public void setImage3Url(String image3Url) {
		this.image3Url = image3Url;
	}

	@Column(name = "image_3_alt_text", length = 60)
	public String getImage3AltText() {
		return this.image3AltText;
	}

	public void setImage3AltText(String image3AltText) {
		this.image3AltText = image3AltText;
	}

	@Column(name = "image_4_url")
	public String getImage4Url() {
		return this.image4Url;
	}

	public void setImage4Url(String image4Url) {
		this.image4Url = image4Url;
	}

	@Column(name = "image_4_alt_text", length = 60)
	public String getImage4AltText() {
		return this.image4AltText;
	}

	public void setImage4AltText(String image4AltText) {
		this.image4AltText = image4AltText;
	}

	@Column(name = "image_5_url")
	public String getImage5Url() {
		return this.image5Url;
	}

	public void setImage5Url(String image5Url) {
		this.image5Url = image5Url;
	}

	@Column(name = "image_5_alt_text", length = 60)
	public String getImage5AltText() {
		return this.image5AltText;
	}

	public void setImage5AltText(String image5AltText) {
		this.image5AltText = image5AltText;
	}

	@Column(name = "image_6_url")
	public String getImage6Url() {
		return this.image6Url;
	}

	public void setImage6Url(String image6Url) {
		this.image6Url = image6Url;
	}

	@Column(name = "image_6_alt_text", length = 60)
	public String getImage6AltText() {
		return this.image6AltText;
	}

	public void setImage6AltText(String image6AltText) {
		this.image6AltText = image6AltText;
	}

	@Column(name = "image_7_url")
	public String getImage7Url() {
		return this.image7Url;
	}

	public void setImage7Url(String image7Url) {
		this.image7Url = image7Url;
	}

	@Column(name = "image_7_alt_text", length = 60)
	public String getImage7AltText() {
		return this.image7AltText;
	}

	public void setImage7AltText(String image7AltText) {
		this.image7AltText = image7AltText;
	}

	@Column(name = "image_8_url")
	public String getImage8Url() {
		return this.image8Url;
	}

	public void setImage8Url(String image8Url) {
		this.image8Url = image8Url;
	}

	@Column(name = "image_8_alt_text", length = 60)
	public String getImage8AltText() {
		return this.image8AltText;
	}

	public void setImage8AltText(String image8AltText) {
		this.image8AltText = image8AltText;
	}

	@Column(name = "seq_no")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hesGripCategoryPackages")
	public Set getHesGripCategoryPackageItemses() {
		return this.hesGripCategoryPackageItemses;
	}

	public void setHesGripCategoryPackageItemses(
			Set hesGripCategoryPackageItemses) {
		this.hesGripCategoryPackageItemses = hesGripCategoryPackageItemses;
	}

}
