package com.idc.hes;

// Generated Mar 10, 2016 5:41:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HesLightingCategories generated by hbm2java
 */
@Entity
@Table(name = "hes_lighting_categories", catalog = "hes_db")
public class HesLightingCategories implements java.io.Serializable {

	private long id;
	private String displayText;
	private String seoName;
	private String imageUrl;
	private String imageAltText;
	private Integer seqNo;
	private Set hesLightingCategoryPackageses = new HashSet(0);

	public HesLightingCategories() {
	}

	public HesLightingCategories(long id, String displayText) {
		this.id = id;
		this.displayText = displayText;
	}

	public HesLightingCategories(long id, String displayText, String seoName,
			String imageUrl, String imageAltText, Integer seqNo,
			Set hesLightingCategoryPackageses) {
		this.id = id;
		this.displayText = displayText;
		this.seoName = seoName;
		this.imageUrl = imageUrl;
		this.imageAltText = imageAltText;
		this.seqNo = seqNo;
		this.hesLightingCategoryPackageses = hesLightingCategoryPackageses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "display_text", nullable = false)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "seo_name")
	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "image_alt_text", length = 60)
	public String getImageAltText() {
		return this.imageAltText;
	}

	public void setImageAltText(String imageAltText) {
		this.imageAltText = imageAltText;
	}

	@Column(name = "seq_no")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hesLightingCategories")
	public Set getHesLightingCategoryPackageses() {
		return this.hesLightingCategoryPackageses;
	}

	public void setHesLightingCategoryPackageses(
			Set hesLightingCategoryPackageses) {
		this.hesLightingCategoryPackageses = hesLightingCategoryPackageses;
	}

}
