package com.idc.hes;

// Generated Mar 10, 2016 5:41:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HesRequestDetails generated by hbm2java
 */
@Entity
@Table(name = "hes_request_details", catalog = "hes_db")
public class HesRequestDetails implements java.io.Serializable {

	private long id;
	private HesRequests hesRequests;
	private String data;

	public HesRequestDetails() {
	}

	public HesRequestDetails(long id, HesRequests hesRequests, String data) {
		this.id = id;
		this.hesRequests = hesRequests;
		this.data = data;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "requests_id", nullable = false)
	public HesRequests getHesRequests() {
		return this.hesRequests;
	}

	public void setHesRequests(HesRequests hesRequests) {
		this.hesRequests = hesRequests;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
