package com.idc.hes;

// Generated Mar 10, 2016 5:41:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HesRequests generated by hbm2java
 */
@Entity
@Table(name = "hes_requests", catalog = "hes_db")
public class HesRequests implements java.io.Serializable {

	private long id;
	private String customerCompany;
	private String customerName;
	private String customerAddress;
	private String customerPhone;
	private String customerAltPhone;
	private String customerEmail;
	private Date requestedDeliveryDate;
	private String specialInstructions;
	private Date requestDate;
	private Set hesRequestDetailses = new HashSet(0);

	public HesRequests() {
	}

	public HesRequests(long id, String customerCompany, String customerName,
			String customerAddress, String customerPhone,
			String customerAltPhone, String customerEmail,
			Date requestedDeliveryDate, Date requestDate) {
		this.id = id;
		this.customerCompany = customerCompany;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerPhone = customerPhone;
		this.customerAltPhone = customerAltPhone;
		this.customerEmail = customerEmail;
		this.requestedDeliveryDate = requestedDeliveryDate;
		this.requestDate = requestDate;
	}

	public HesRequests(long id, String customerCompany, String customerName,
			String customerAddress, String customerPhone,
			String customerAltPhone, String customerEmail,
			Date requestedDeliveryDate, String specialInstructions,
			Date requestDate, Set hesRequestDetailses) {
		this.id = id;
		this.customerCompany = customerCompany;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerPhone = customerPhone;
		this.customerAltPhone = customerAltPhone;
		this.customerEmail = customerEmail;
		this.requestedDeliveryDate = requestedDeliveryDate;
		this.specialInstructions = specialInstructions;
		this.requestDate = requestDate;
		this.hesRequestDetailses = hesRequestDetailses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "customer_company", nullable = false)
	public String getCustomerCompany() {
		return this.customerCompany;
	}

	public void setCustomerCompany(String customerCompany) {
		this.customerCompany = customerCompany;
	}

	@Column(name = "customer_name", nullable = false)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_address", nullable = false)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "customer_phone", nullable = false, length = 20)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "customer_alt_phone", nullable = false, length = 20)
	public String getCustomerAltPhone() {
		return this.customerAltPhone;
	}

	public void setCustomerAltPhone(String customerAltPhone) {
		this.customerAltPhone = customerAltPhone;
	}

	@Column(name = "customer_email", nullable = false)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "requested_delivery_date", nullable = false, length = 19)
	public Date getRequestedDeliveryDate() {
		return this.requestedDeliveryDate;
	}

	public void setRequestedDeliveryDate(Date requestedDeliveryDate) {
		this.requestedDeliveryDate = requestedDeliveryDate;
	}

	@Column(name = "special_instructions")
	public String getSpecialInstructions() {
		return this.specialInstructions;
	}

	public void setSpecialInstructions(String specialInstructions) {
		this.specialInstructions = specialInstructions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_date", nullable = false, length = 19)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hesRequests")
	public Set getHesRequestDetailses() {
		return this.hesRequestDetailses;
	}

	public void setHesRequestDetailses(Set hesRequestDetailses) {
		this.hesRequestDetailses = hesRequestDetailses;
	}

}
