package com.idc.hes;

// Generated Mar 10, 2016 5:41:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HesTruckCategoryPackageItems generated by hbm2java
 */
@Entity
@Table(name = "hes_truck_category_package_items", catalog = "hes_db")
public class HesTruckCategoryPackageItems implements java.io.Serializable {

	private long id;
	private HesTruckCategoryPackages hesTruckCategoryPackages;
	private String displayText;
	private String seoName;
	private Integer defaultCount;
	private Integer priority;
	private Integer seqNo;

	public HesTruckCategoryPackageItems() {
	}

	public HesTruckCategoryPackageItems(long id,
			HesTruckCategoryPackages hesTruckCategoryPackages,
			String displayText) {
		this.id = id;
		this.hesTruckCategoryPackages = hesTruckCategoryPackages;
		this.displayText = displayText;
	}

	public HesTruckCategoryPackageItems(long id,
			HesTruckCategoryPackages hesTruckCategoryPackages,
			String displayText, String seoName, Integer defaultCount,
			Integer priority, Integer seqNo) {
		this.id = id;
		this.hesTruckCategoryPackages = hesTruckCategoryPackages;
		this.displayText = displayText;
		this.seoName = seoName;
		this.defaultCount = defaultCount;
		this.priority = priority;
		this.seqNo = seqNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_id", nullable = false)
	public HesTruckCategoryPackages getHesTruckCategoryPackages() {
		return this.hesTruckCategoryPackages;
	}

	public void setHesTruckCategoryPackages(
			HesTruckCategoryPackages hesTruckCategoryPackages) {
		this.hesTruckCategoryPackages = hesTruckCategoryPackages;
	}

	@Column(name = "display_text", nullable = false)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "seo_name")
	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

	@Column(name = "default_count")
	public Integer getDefaultCount() {
		return this.defaultCount;
	}

	public void setDefaultCount(Integer defaultCount) {
		this.defaultCount = defaultCount;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "seq_no")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

}
